# [core]
# Enable all compact filters.
blockfilterindex=1
# Maintain coinstats index used by the gettxoutsetinfo RPC.
coinstatsindex=1
# Maintain a full transaction index, used by the getrawtransaction rpc call.
txindex=1

# Run in the background as a daemon and accept commands.
daemon=1
# Wait for initialization to be finished before exiting. This implies -daemon.
daemonwait=1

# [network]
# Serve compact block filters to peers per BIP 157.
# NOTE: enabling this will force blockfilterindex on
peerblockfilters=1

# [rpc]
# Accept command line and JSON-RPC commands.
server=1

# [Sections]
# Most options automatically apply to mainnet, testnet, and regtest networks.
# If you want to confine an option to just one network,
# you should add it in the relevant section.
# EXCEPTIONS: addnode, connect, port, bind, rpcport, rpcbind and wallet
# only apply to mainnet unless they appear in the appropriate section below.

# Options only for mainnet
[main]

# Set database cache size in megabytes;
# machines sync faster with a larger cache.
dbcache=4096

# Keep the transaction memory pool below <n> megabytes.
maxmempool=4096

# Do not keep transactions in the mempool longer than <n> hours.
mempoolexpiry=5124

# Options only for testnet
[test]

# Set database cache size in megabytes;
# machines sync faster with a larger cache.
dbcache=4096

# [network]
# Relay and mine non-standard transactions (testnet/regtest only.)
acceptnonstdtxn=1

# Options only for regtest
[regtest]

# [network]
# Relay and mine non-standard transactions (testnet/regtest only.)
acceptnonstdtxn=1
